env:
  global:
    - CC_TEST_REPORTER_ID=3b45653e81ddcd98c5c278987736bfaa1ca2959e36a7209dca3f23b98b5ef0d5
language: node_js
node_js:
  - "stable"
services:
  - "postgres"
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - yarn add sequelize-cli -g
  - psql -c "CREATE DATABASE sms_test;" -U postgres
  - sequelize db:migrate --env test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
after_success:
  - yarn test:cover
